# 아래 client-id와 client-secret은 예시로 넣은 더미데이터입니다. 참고만 부탁드려요.
spring:
  h2:
    console:
      enabled: true
      path: /console
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  server:
    port: 8080
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 958180173202-sii4epowero1eouvvjrlrnt27sikub08k.apps.googleusercontent.com
            client-secret: k0asdfag801WdcJF8k9ST_8SG9
          facebook:
            client-id: 11612612521462
            client-secret: 6578235217c5c365a98c51b02d0308ac
custom:
  oauth2:
    kakao:
#      authorization-grant-type: authorization_code
      scope: profile
#      redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
      redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
      client-name: Kakao
      client-authentication-method: POST
      client-id: 434939a33926013691dc9ee130297322
      client-secret: Ay0dUxUDGjJtH74dIHLUUTzYrRcZUY5X
    naver:
      client-id: B5yvH3Zaweyawerawwe6repj4z0L
      client-secret: sArXFasdfawef


devtools:
  livereload:
    enabled: true